# Generated by Django 3.2 on 2024-10-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('chat', '0003_alter_chat_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.ManyToManyField(related_name='messagetasks', to='tasks.Task')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.messagetasks'),
        ),
    ]
