# Generated by Django 3.2 on 2024-10-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20241024_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
