# Generated by Django 3.2 on 2024-10-29 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20241029_2240'),
        ('chat', '0006_messagetasks_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='calender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.calender'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.DeleteModel(
            name='MessageTasks',
        ),
    ]
